# Generated by Django 5.0.6 on 2024-05-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_tyoe',
            new_name='doc_type',
        ),
    ]
