# Generated by Django 5.0.6 on 2024-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_doc_tyoe_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='birthday',
            field=models.CharField(choices=[('P', 'Prontuário'), ('R', 'Relatório'), ('A', 'Arquivo')], default='P', max_length=1),
        ),
    ]
